apiVersion: v1
kind: Namespace
metadata:
  name: gocd-simple
  labels:
    app: gocd-simple

---
apiVersion: v1
kind: Service
metadata:
  name: gocd-server
  namespace: gocd-simple
  labels:
    app: gocd-server
spec:
  type: LoadBalancer
  ports:
  - port: 8153
    targetPort: 8153
    name: http
  - port: 8154
    targetPort: 8154
    name: https
  selector:
    app: gocd-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocd-server
  namespace: gocd-simple
  labels:
    app: gocd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocd-server
  template:
    metadata:
      labels:
        app: gocd-server
    spec:
      containers:
      - name: gocd-server
        image: gocd/gocd-server:v23.3.0
        ports:
        - containerPort: 8153
        - containerPort: 8154
        env:
        - name: GO_SERVER_SYSTEM_PROPERTIES
          value: "-Dgo.plugin.upload.enabled=true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
